version: '3'
volumes:
  bundle: {}
  node_modules: {}
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    working_dir: /app
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -b0
    ports:
      - '3000:3000'
