version: '3'
volumes:
  bundle: {}
  node_modules: {}
  tmp: {}
  postgres_data: {}
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - tmp:/app/tmp
    working_dir: /app
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -b0
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=currency_quotation_development
