default: &default
  host: database
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: postgres

development:
  <<: *default
  database: currency_quotation_development

test:
  <<: *default
  database: currency_quotation_test

production:
  url: <%= ENV['DATABASE_URL'] %>
